export const RED = "#ff0000"
export const DARK_BLUE = "#000034"
export const LIGHT_BLUE = "#D4EBF2"
export const DARK_RED = "#8B0000"
export const PALE_PURPLE = "#f7e9f7"
export const PALE_WHITE = "#fdfdfd"
export const WHITE = "#fffffff"