export const TEMPLATE_AVATAR_URL = "https://i.pinimg.com/564x/d4/ef/25/d4ef25443bf99a718adabc8b1473a6aa.jpg"
export const BASE_URL = "http://192.168.10.233:3001";
export const LOGIN_ENDPOINT = BASE_URL + "/login";
export const REGISTRATION_ENDPOINT = BASE_URL + "/register";
export const REGISTER_ENDPOINT = "/auth/register";
export const GET_ALL_BRANDS_ENDPOINT = BASE_URL + "/labels";
export const GET_ALL_PRODUCTS_ENDPOINT = BASE_URL + "/products";
export const GET_USER_DETAILS = BASE_URL + "/users";
export const UPDATE_USER_DETAILS = BASE_URL + "/users";
export const CREATE_ORDER = BASE_URL + "/orders";
export const API_TIMEOUT = 5000;